kind: ConfigMap
apiVersion: v1
metadata:
  name: backup-config
data:
  backup.subdir: "/"
  backup.dirname: "+etcd-backup-%F-%H-%M-%S"
  backup.expiretype: "days"
  backup.keepdays: "30"
  backup.keepcount: "10"
